language: python

python:
  - "3.6"
  
branches:
  only:
    - master
    
install:
  - pip install -r requirements.txt
  - echo -e "machine github.com\n  login ${GITHUB_API_KEY}" > ~/.netrc

script:
  - mkdocs build --clean
  
depoly:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_API_KEY
  repo: https://$GITHUB_API_KEY@$REPO
  on:
    branch: master
  
