language: python

python:
  - "3.6"
  
branches:
  only:
    - master

    
install:
  - pip install -r requirements.txt
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs build --clean

after_success:  |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd site
    git init
    git add .
    git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -m "Auto Deployment"
    git push -f -q https://$GITHUB_NAME:$GITHUB_TOKEN@$REPO master
    cd "$TRAVIS_BUILD_DIR"
  fi
  
