language: python

python:
  - "3.6"
  
branches:
  only:
    - master
    
install:
  - pip install -r requirements.txt
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs build --clean
  
depoly:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  repo: doragd/doragd.github.io
  on:
    branch: master
  
