# Project Information
site_name: Doragd (Guodun Li)
site_url: https://doragd.github.io
site_description: Doragd's Blog and Wiki.
site_author: Doragd

# Repository
repo_url: https://github.com/doragd/doragd.github.io
repo_name: Doragd-Wiki
edit_uri: 'blob/master/docs'

# Copyright
copyright: 'Copyright &copy; 2019 - 2023 Doragd'


# Nav
nav:
  - 首页:
    - 关于我: index.md
  - 数据结构与算法:
    - LeetCode: archive/leetcode.md
  - 数理基础:
    - 概率论读书笔记: archive/math-statistics.md
  - 自然语言处理:
    - CS224N:
      - 课程导览: archive/cs224n.md
  - Daily Paper:
    - Paper List: archive/paper-list.md
    - ACL论文速览:
      - ACL2019: archive/acl2019-quick-review.md
    - EMNLP论文速览:
      - EMNLP2019: archive/emnlp2019-quick-review.md
    - NAACL论文速览:
      - NAACL2019: archive/naacl2019-quick-review.md
    - 论文选读:
      - Stylized Image Caption: archive/stylized-image-caption.md
  - 其他:
    - 磕盐方法论: archive/science-methodology.md
    - Wiki效果测试: archive/wiki-test.md
    - Polyaxon食谱: archive/polyaxon-cookbook.md
    - Python极客时间笔记: archive/python-geek-time.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  feature:
    tabs: true
  palette:
    primary: white
    accent: red
  include_search_page: false
  search_index_only: true
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

    
# Extension
markdown_extensions:
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
      
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/doragd'
    - type: 'twitter'
      link: 'https://twitter.com/ChangeGd'
  disqus: 'reDoragd'
  manifest: 'manifest.webmanifest'


